apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: lnd
  name: lnd-pvc
  namespace: bitcoin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: lnd-conf
  namespace: bitcoin
data:
  lnd.conf: W0FwcGxpY2F0aW9uIE9wdGlvbnNdCmxpc3Rlbj0wLjAuMC4wOjk3MzUKcnBjbGlzdGVuPTAuMC4wLjA6MTAwMDkKcmVzdGxpc3Rlbj0wLjAuMC4wOjgwODAKZXh0ZXJuYWxpcD0xOTguMjUxLjc2LjI0CmFsaWFzPXNjaG11Y2tlbGUKCltCaXRjb2luXQpiaXRjb2luLm5vZGU9Yml0Y29pbmQKYml0Y29pbi5hY3RpdmU9dHJ1ZQpiaXRjb2luLm1haW5uZXQ9dHJ1ZQoKW0JpdGNvaW5kXQpiaXRjb2luZC5ycGNob3N0PWJpdGNvaW5kOjgzMzIKYml0Y29pbmQucnBjdXNlcj1DaHJpc3RpbmVNYWRlbGVpbmVPZGV0dGVMYWxsb3VldHRlCmJpdGNvaW5kLnJwY3Bhc3M9MWVyamFudmllcjE5NTYKYml0Y29pbmQuem1xcHVicmF3YmxvY2s9dGNwOi8vYml0Y29pbmQ6MjgzMzIKYml0Y29pbmQuem1xcHVicmF3dHg9dGNwOi8vYml0Y29pbmQ6MjgzMzMKYml0Y29pbmQuZXN0aW1hdGVtb2RlPUNPTlNFUlZBVElWRQo=
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lnd
  namespace: bitcoin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lnd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lnd
    spec:
      containers:
      - image: lightninglabs/lnd:v0.17.4-beta
        imagePullPolicy: IfNotPresent
        name: lnd
        ports:
        - containerPort: 10009
          protocol: TCP
        - containerPort: 9735
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: lnd-vol
          mountPath: /root/.lnd
        - name: lnd-conf
          mountPath: "/root/.lnd/lnd.conf"
          subPath: lnd.conf
          readOnly: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      volumes:
      - name: lnd-vol
        persistentVolumeClaim:
          claimName: lnd-pvc
      - name: lnd-conf
        secret:
          secretName: lnd-conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lnd
  name: lnd
  namespace: bitcoin
spec:
  type: NodePort
  selector:
    app: lnd
  ports:
  - name: rpc
    port: 10009
    targetPort: 10009
    nodePort: 30109
  - name: p2p
    port: 9735
    targetPort: 9735
    nodePort: 30735
  - name: rest
    port: 8080
    targetPort: 8080
    nodePort: 30808
  
