apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: lnd
  name: lnd-pvc
  namespace: bitcoin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: lnd-conf
  namespace: bitcoin
data:
  lnd.conf: W0JpdGNvaW5dCmJpdGNvaW4ubm9kZT1iaXRjb2luZApiaXRjb2luLmFjdGl2ZT10cnVlCgpbQml0Y29pbmRdCmJpdGNvaW5kLnJwY2hvc3Q9Yml0Y29pbmQ6ODMzMgpiaXRjb2luZC5ycGN1c2VyPUNocmlzdGluZU1hZGVsZWluZU9kZXR0ZUxhbGxvdWV0dGUKYml0Y29pbmQucnBjcGFzcz0xZXJqYW52aWVyMTk1NgpiaXRjb2luZC56bXFwdWJyYXdibG9jaz10Y3A6Ly9iaXRjb2luZDoyODMzMgpiaXRjb2luZC56bXFwdWJyYXd0eD10Y3A6Ly9iaXRjb2luZDoyODMzMwpiaXRjb2luZC5lc3RpbWF0ZW1vZGU9Q09OU0VSVkFUSVZFCg==
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lnd
  namespace: bitcoin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lnd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lnd
    spec:
      containers:
      - image: lightninglabs/lnd:v0.17.4-beta
        imagePullPolicy: IfNotPresent
        name: lnd
        ports:
        - containerPort: 10009
          protocol: TCP
        - containerPort: 9735
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: lnd-vol
          mountPath: /root/.lnd
        - name: lnd-conf
          mountPath: "/root/.lnd/lnd.conf"
          subPath: lnd.conf
          readOnly: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      volumes:
      - name: lnd-vol
        persistentVolumeClaim:
          claimName: lnd-pvc
      - name: lnd-conf
        secret:
          secretName: lnd-conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lnd
  name: lnd
  namespace: bitcoin
spec:
  type: NodePort
  selector:
    app: lnd
  ports:
  - name: rpc
    port: 10009
    targetPort: 10009
    nodePort: 30109
  - name: p2p
    port: 9735
    targetPort: 9735
    nodePort: 30735
  