apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mempool-db
  name: mempool-db-pvc
  namespace: bitcoin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mempool-db
  namespace: bitcoin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mempool-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mempool-db
    spec:
      containers:
      - image: mariadb:10.5.21
        imagePullPolicy: IfNotPresent
        name: mempool-db
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: topsecret
        resources: {}
        volumeMounts:
        - name: mempool-db-vol
          mountPath: /var/lib/mysql
      restartPolicy: Always
      volumes:
      - name: mempool-db-vol
        persistentVolumeClaim:
          claimName: mempool-db-pvc
