apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: electrs
  name: electrs-pvc
  namespace: bitcoin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 90Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: electrs-conf
  namespace: bitcoin
data:
  config.toml: bG9nX2ZpbHRlcnMgPSAiSU5GTyIKbmV0d29yayA9ICJiaXRjb2luIgpkYWVtb25fcnBjX2FkZHIgPSAiYml0Y29pbmQ6ODMzMiIKZGFlbW9uX3AycF9hZGRyID0gImJpdGNvaW5kOjgzMzMiCmVsZWN0cnVtX3JwY19hZGRyID0gIjAuMC4wLjA6NTAwMDEiCnNlcnZlcl9iYW5uZXIgPSAiZWxlY3RycyB2MC4xMC4zIgpkYl9kaXIgPSAiL2RhdGEvZGIiCmF1dGggPSAiQ2hyaXN0aW5lTWFkZWxlaW5lT2RldHRlTGFsbG91ZXR0ZToxZXJqYW52aWVyMTk1NiIK
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: electrs
  namespace: bitcoin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: electrs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: electrs
    spec:
      containers:
      - image: philipcristiano/electrs:0.10.3
        imagePullPolicy: IfNotPresent
        name: electrs
        ports:
        - containerPort: 50001
          protocol: TCP
        env:
        resources: {}
        volumeMounts:
        - name: electrs-vol
          mountPath: /data
        - name: electrs-conf
          mountPath: "/root/.electrs/config.toml"
          subPath: config.toml
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: electrs-vol
        persistentVolumeClaim:
          claimName: electrs-pvc
      - name: electrs-conf
        secret:
          secretName: electrs-conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: electrs
  name: electrs
  namespace: bitcoin
spec:
  type: NodePort
  selector:
    app: electrs
  ports:
  - name: rpc
    port: 50001
    targetPort: 50001
    nodePort: 30001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
  name: electrs-tls
  namespace: bitcoin
spec:
  tls:
  - hosts:
      - 192.168.178.19
    secretName: electrs-tls
  rules:
  - host: 192.168.178.19
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: electrs
            port:
              number: 50001
