apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: lit
  name: lit-pvc
  namespace: bitcoin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: lnd
  name: lnd-pvc
  namespace: bitcoin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: lit-conf
  namespace: bitcoin
data:
  lit.conf: I1tBcHBsaWNhdGlvbiBPcHRpb25zXQpsbmQubGlzdGVuPTAuMC4wLjA6OTczNQpsbmQucnBjbGlzdGVuPTAuMC4wLjA6MTAwMDkKbG5kLnJlc3RsaXN0ZW49MC4wLjAuMDo4MDgwCmxuZC5leHRlcm5hbGlwPTE5OC4yNTEuNzYuMjQKbG5kLmFsaWFzPXNjaG11Y2tlbGUKCiNbQml0Y29pbl0KbG5kLmJpdGNvaW4ubm9kZT1iaXRjb2luZApsbmQuYml0Y29pbi5hY3RpdmU9dHJ1ZQpsbmQuYml0Y29pbi5tYWlubmV0PXRydWUKCiNbQml0Y29pbmRdCmxuZC5iaXRjb2luZC5ycGNob3N0PWJpdGNvaW5kOjgzMzIKbG5kLmJpdGNvaW5kLnJwY3VzZXI9Q2hyaXN0aW5lTWFkZWxlaW5lT2RldHRlTGFsbG91ZXR0ZQpsbmQuYml0Y29pbmQucnBjcGFzcz0xZXJqYW52aWVyMTk1NgpsbmQuYml0Y29pbmQuem1xcHVicmF3YmxvY2s9dGNwOi8vYml0Y29pbmQ6MjgzMzIKbG5kLmJpdGNvaW5kLnptcXB1YnJhd3R4PXRjcDovL2JpdGNvaW5kOjI4MzMzCmxuZC5iaXRjb2luZC5lc3RpbWF0ZW1vZGU9Q09OU0VSVkFUSVZFCgojIEFwcGxpY2F0aW9uIE9wdGlvbnMKaHR0cHNsaXN0ZW49MC4wLjAuMDo4NDQzCnVpcGFzc3dvcmQ9dG9wc2VjcmV0CnRsc2NlcnRwYXRoPX4vLmxpdC90bHMuY3J0CnRsc2tleXBhdGg9fi8ubGl0L3Rscy5rZXkKbG5kLW1vZGU9aW50ZWdyYXRlZAoKIyBMbmQKbG5kLmxuZGRpcj1+Ly5sbmQKbG5kLmRlYnVnbGV2ZWw9ZGVidWcKCiMgTG9vcApsb29wLmxvb3BvdXRtYXhwYXJ0cz01CgojIFBvb2wKcG9vbC5uZXdub2Rlc29ubHk9dHJ1ZQoKIyBGYXJhZGF5CmZhcmFkYXkubWluX21vbml0b3JlZD00OGgKCiMgRmFyYWRheSAtIGJpdGNvaW4KZmFyYWRheS5jb25uZWN0X2JpdGNvaW49dHJ1ZQpmYXJhZGF5LmJpdGNvaW4uaG9zdD1iaXRjb2luZDo4MzMyCmZhcmFkYXkuYml0Y29pbi51c2VyPUNocmlzdGluZU1hZGVsZWluZU9kZXR0ZUxhbGxvdWV0dGUKZmFyYWRheS5iaXRjb2luLnBhc3N3b3JkPTFlcmphbnZpZXIxOTU2Cg==
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lit
  namespace: bitcoin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lit
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lit
    spec:
      containers:
      - image: lightninglabs/lightning-terminal:v0.12.4-alpha
        imagePullPolicy: IfNotPresent
        name: lit
        ports:
        - containerPort: 10009
          protocol: TCP
        - containerPort: 9735
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: lit-vol
          mountPath: /root/.lit
        - name: lnd-vol
          mountPath: /root/.lnd
        - name: lit-conf
          mountPath: /root/.lit/lit.conf
          subPath: lit.conf
          readOnly: true
        - name: tls-crt
          mountPath: /root/.lit/tls.crt
          subPath: tls.crt
          readOnly: true
        - name: tls-key
          mountPath: /root/.lit/tls.key
          subPath: tls.key
          readOnly: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      volumes:
      - name: lit-vol
        persistentVolumeClaim:
          claimName: lit-pvc
      - name: lnd-vol
        persistentVolumeClaim:
          claimName: lnd-pvc
      - name: lit-conf
        secret:
          secretName: lit-conf
      - name: tls-crt
        secret:
          secretName: lightning.schmuckele.nl-tls
      - name: tls-key
        secret:
          secretName: lightning.schmuckele.nl-tls
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lit
  name: lit
  namespace: bitcoin
spec:
  type: NodePort
  selector:
    app: lit
  ports:
  - name: rpc
    port: 10009
    targetPort: 10009
    nodePort: 30109
  - name: p2p
    port: 9735
    targetPort: 9735
    nodePort: 30735
  - name: rest
    port: 8080
    targetPort: 8080
    nodePort: 30808
  - name: ui
    port: 8443
    targetPort: 8443
    nodePort: 30844
