apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ord
  name: ord-pvc
  namespace: bitcoin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ord
  namespace: bitcoin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ord
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ord
    spec:
      containers:
      - image: bihalu/ord:0.16.0
        imagePullPolicy: IfNotPresent
        name: ord
        command: 
        - ord
        args:
        - server
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: ORD_BITCOIN_RPC_URL
          value: "bitcoind:8332"
        - name: ORD_BITCOIN_RPC_USERNAME
          value: "ChristineMadeleineOdetteLallouette"
        - name: ORD_BITCOIN_RPC_PASSWORD
          value: "1erjanvier1956"
        resources: {}
        volumeMounts:
        - name: ord-vol
          mountPath: /root/.local/share/ord
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ord-vol
        persistentVolumeClaim:
          claimName: ord-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ord
  name: ord
  namespace: bitcoin
spec:
  type: NodePort
  selector:
    app: ord
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30380
  